sensio_framework_extra:
    router:      { annotations: false }
    # Because of temporary bug in Symfony 4.1 sensio/framework-extra-bundle 5.2
    # http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle
    # [How to fix Symfony 3.4 @Route and @Method deprecation](https://stackoverflow.com/questions/51171934/how-to-fix-symfony-3-4-route-and-method-deprecation)
    # [Symfony: Deprecated @Route and @Method Annotations](https://medium.com/@nebkam/symfony-deprecated-route-and-method-annotations-4d5e1d34556a)
