#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Using YAML config as Annotation is failing

# hello:
    # path: /
    # controller: App\Controller\HelloController::index

# app_lucky_number:
    # path: /lucky/number/{max}
    # controller: App\Controller\LuckyController::number
